### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by laura-dietz** [tuckerowens/trec-car-eval#2]
I followed the instructions but I get this error message.

[INFO] Compiling 9 source files to /home/dietz/datasci/BryanTuckerBahram/trec-eval/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.073s
[INFO] Finished at: Mon Feb 13 15:18:29 EST 2017
[INFO] Final Memory: 25M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project trec-eval: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.8
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by tuckerowens** [comment]
The project is configured to build under Java 8. Moved to Java 7 in 3f5a6d3d2655594b858b81a6a8b717c5ea5ca0da

If that doesn't work, back to the drawing board.

**Comment by laura-dietz** [comment]
The information that was missing is "Prerequirement Java 8" - no prob, you just need to add it to the installation instructions.
